### ISSUE TITLE
Firefox release?

### ISSUE THREAD

**Issue by animalillo** [camin-mccluskey/wework-booking-extension#1]
It would be nice to have a firefox release, since firefox extension engine is very similar to the chrome one it shouldn't be too complicated to support

**Comment by camin-mccluskey** [comment]
I have to be honest, this project was to scratch my own itch with WeWork's terrible booking UX. I don't really have the time to port this to Firefox and I don't think it's particularly high ROI in any case. If you'd like a Firefox version you're very welcome to fork the logic here, port it over and publish under your own name 🙂

![Screenshot 2024-04-02 at 14 11 49](https://github.com/camin-mccluskey/wework-booking-extension/assets/18604525/775f0cbd-31d9-42ca-8d96-7754d5d97e2d)
